spring:
  application:
    name: athena-mine-worker-service
  graphql:
    schema:
      locations: "classpath:graphql/**/"
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reactive_mine_job_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

github:
  token: ${GITHUB_TOKEN}