spring:
  application:
    name: athena-mine-worker-service
  graphql:
    schema:
      locations: "classpath:graphql/**/"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mine_job_db
    username: postgres
    password: 3011030216
  jpa:
    hibernate:
      ddl-auto: none

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

github:
  token: ${GITHUB_TOKEN}